presubmits:
  - name: pull-ti-community-prow-validate-prow-yaml
    decorate: true
    run_if_changed: 'configs/prow-dev/'
    branches:
      - ^master$
    spec:
      containers:
        - image: gcr.io/k8s-prow/checkconfig:v20201217-2de500de27
          command:
            - /checkconfig
          args:
            - --plugin-config=configs/prow-dev/config/plugins.yaml
            - --config-path=configs/prow-dev/config/config.yaml
            - --job-config-path=configs/prow-dev/jobs
            - --warnings=validate-urls
            - --warnings=unknown-fields
            - --warnings=duplicate-job-refs
  - name: pull-ti-community-prow-rerere
    decorate: true
    always_run: true
    trigger: "(?mi)^/(merge|rerere)\\s*$"
    rerun_command: "/rerere"
    max_concurrency: 1
    branches:
      - ^master$
    spec:
      containers:
        - image: rustinliu/rerere-component:v0.17.0
          command:
            - rerere
          args:
            - --github-token-path=/etc/github/token
            - --dry-run=false
            - --github-endpoint=https://api.github.com
            - --require-contexts=build
            - --require-contexts=lint
            - --labels=status/can-merge
          volumeMounts:
            - name: github-token
              mountPath: /etc/github
              readOnly: true
      volumes:
        - name: github-token
          secret:
            secretName: github-token
postsubmits:
  - name: post-ti-community-prow-deploy-prow
    run_if_changed: 'configs/prow-dev/cluster/'
    decorate: true
    branches:
      - ^master$
    max_concurrency: 1
    spec:
      containers:
        - image: google/cloud-sdk:319.0.0
          command:
            - scripts/deploy.sh
          args:
            - --confirm
            - --config=trusted
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /creds/service-account.json
          volumeMounts:
            - name: creds
              mountPath: /creds
      volumes:
        - name: creds
          secret:
            secretName: deployer-credentials
    annotations:
      description: deploys the configured version of prow by running scripts/deploy.sh