name: Web

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  weblint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        users: actions/setup-node@v1
        with:
          node-version: '12'
        run: npm install
      - name: Run lint
        run: npm run lint